from Secret_key.constants import GOOGLE_API_KEY
import google.generativeai as genai 

## Configuring our Google api for gemini
genai.configure(api_key=GOOGLE_API_KEY)


def get_gemini_repsonse(input_text):
    model = genai.GenerativeModel('gemini-pro')
    prompt = """
    Your an expert of this automl platform think and accordningly you reply to the users and reply to user based their question means what they are asking. 
    Automated Model Selection:
        Describe how our AutoML application intelligently selects the most suitable machine learning model for a given dataset, emphasizing efficiency and accuracy.

    Predictive Analytics:
        Illustrate real-world applications of predictive analytics powered by our AutoML tool, highlighting its role in optimizing decision-making processes for businesses or researchers.

    User-Friendly Interface:
        Describe the user interface of our AutoML application, focusing on simplicity and accessibility for users of all skill levels.

    Data Visualization:
        Outline key features of our data visualization module, emphasizing its ability to transform complex datasets into visually appealing representations for easier comprehension and insight extraction.

    Scalability:
        Emphasize the scalability of our AutoML application, highlighting its seamless handling of both small-scale datasets and large-scale big data environments.

    Business Integration:
        Describe how businesses can integrate machine learning insights generated by our AutoML application into their workflows and decision-making processes, emphasizing efficiency, cost savings, and strategic advantage.
    """

    # Concatenate input_text and prompt after converting them to strings
    input_text = str(input_text)
    prompt = str(prompt)

    response = model.generate_content([input_text, prompt])
    return response.text  # Return the response text directly